# Generated by Django 5.0.7 on 2024-08-31 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_remove_order_total_price_remove_orderitem_item_price_and_more'),
        ('profiles', '0004_alter_customer_email_alter_customer_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='profiles.customer'),
        ),
    ]
