# Generated by Django 5.0.7 on 2024-09-01 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='is_ordered',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
