# Generated by Django 5.0.7 on 2024-09-01 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0009_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seller',
        ),
    ]
