# Generated by Django 5.0.7 on 2024-09-05 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0013_alter_product_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
