# Generated by Django 5.0.7 on 2024-09-05 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0014_remove_product_image_product_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image_url',
            new_name='image',
        ),
    ]
