# Generated by Django 5.0.7 on 2025-01-06 09:52

import categories.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0015_rename_image_url_product_image'),
        ('profiles', '0008_alter_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(default=categories.models.get_default_seller, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='profiles.customer'),
        ),
    ]
